"""Recomputes every stored embedding in place with the currently configured embedder.

Why this exists as a separate script rather than "just re-run seed.py": seed.py inserts, so it
only works against an empty database, and a database that has been used has rows seed.py never
created — lessons, flashcards and quiz attempts generated by the pipeline and by real learner
answers. Wiping those to change an embedding model is not an acceptable migration path, and it
is not available at all on a deployed database.

Vectors written by different embedders are not comparable: a pgvector query embedded with
bge-small against rows still holding hash-placeholder vectors returns ranked nonsense, silently
and with no error. So after changing MENTRA_EMBED (or the model behind it), every embedded
column has to be rewritten before any similarity search is trustworthy. Run this, not seed.py.

Idempotent — safe to run repeatedly. Batched per table so one ONNX call covers many rows.

    python scripts/reembed.py
"""

import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import select  # noqa: E402

from mentra_embed import active_backend, embed_documents  # noqa: E402

from app.database import async_session  # noqa: E402
from app.models import Topic, TutorProfile, VideoTranscriptChunk  # noqa: E402

BATCH = 64


async def _rewrite(db, rows, text_of, set_on):
    """Embed `rows` in batches and assign the vector back onto each row.

    text_of/set_on are passed in rather than hardcoded because each table derives its embedding
    text differently, and those derivations must stay identical to the ones in seed.py — if they
    drift, re-embedding silently changes what a row means.
    """
    for start in range(0, len(rows), BATCH):
        chunk = rows[start : start + BATCH]
        for row, vector in zip(chunk, embed_documents([text_of(row) for row in chunk])):
            set_on(row, vector)
        await db.flush()
    return len(rows)


async def main():
    print(f"Re-embedding with backend: {active_backend()}")
    async with async_session() as db:
        topics = list((await db.execute(select(Topic))).scalars().all())
        n_topics = await _rewrite(
            db,
            topics,
            lambda t: t.name,
            lambda t, v: setattr(t, "content_embedding", v),
        )

        tutors = list((await db.execute(select(TutorProfile))).scalars().all())
        n_tutors = await _rewrite(
            db,
            tutors,
            lambda t: " ".join(t.subjects or []) + " " + (t.name or ""),
            lambda t, v: setattr(t, "specialty_embedding", v),
        )

        chunks = list((await db.execute(select(VideoTranscriptChunk))).scalars().all())
        n_chunks = await _rewrite(
            db,
            chunks,
            lambda c: c.video_title + " " + c.chunk_text,
            lambda c, v: setattr(c, "chunk_embedding", v),
        )

        await db.commit()

    print(f"Re-embedded {n_topics} topics, {n_tutors} tutors, {n_chunks} transcript chunks.")


if __name__ == "__main__":
    asyncio.run(main())
